faucetsdn/forch

forch/faucetizer.py
Auth module will send "None" segment in case of authentication failure and expiration. Hence resetting port policies to default when segment argument is None.
=> Reset port policies if segment is None

forch/faucet_event_client.py, forch/forchestrator.py
In _process_faucet_event(), event will never be assigned if exception happens. Printing out event if exception happens in lower level functions.
=> Improve exception handling in processing event

forch/faucet_state_collector.py
We cannot gurantee that the acces switch exists by the time when this method is called.
=> Do not assert existence of access switch for a MAC

forch/faucetizer.py
Augmented include files, mainly the .yaml files for the ACLs, were written to FORCH_CONFIG_DIR previously. Now making forch write them to FAUCET_CONFIG_DIR instead.
=> Output augmented include files to faucet directory

bin/stack_functions, etc/test_stack.out, forch/forch_metrics.py, forch/forchestrator.py, testing/test_access, testing/test_stack
Example of varz:
faucet_config_warning_count 2.0
faucet_config_warning{key="faucet_dp_mac",message="faucet_dp_mac for DPs are not identical"} 1.0
faucet_config_warning{key="nz-kiwi-t1sw2",message="faucet_dp_mac not defined"} 1.0
=> Expose faucet config warning through API and Varz

bin/compile_ovs, bin/stack_functions, etc/Dockerfile.controller, etc/Dockerfile.faucet, etc/docker_images.txt, etc/test_stack.out
Makes some baseline changes to stack testing in prep for faucet update.  Mosty adds --immediate-mode and vlan filter to tcpdump.
=> Improve stack test checking

.stickler.yml, testing/python_lib/integration_base.py, testing/python_lib/test_failscale.py, testing/python_lib/test_fot.py
Something is wonky with the python logger and the unit tests... it will deadlock sometimes when there's a lot of output. This just uses the print() method instead and makes the logs somewhat more verbose.
=> Use print() rather than logger

forch/faucet_event_client.py, forch/forch_metrics.py, forch/forchestrator.py, forch/utils.py, forch/varz_state_collector.py, testing/python_lib/test_event.py, testing/python_lib/unit_base.py, testing/test_base
Every time Forch connects to the socket it will restore the states from varzs. So I think we can remove the exception here.
=> Do not raise exception in case of out-of-sequence Faucet event

forch/faucetizer.py, forch/utils.py
For example, if the included file is `foo/bar/uniform.yaml`, with this PR, Forch will write it to `/etc/faucet/foo/bar/uniform.yaml`. Currently the output path is `/etc/faucet/uniform.yaml`.
=> Preserve directory path of included file in Faucet config

bin/stack_functions, etc/test_stack.out, forch/faucet_event_client.py
Fixing the problem that inner PORT_CHANGE event does not have a dp_id info.
=> Get dpid from wrapping event for port state handling

forch/__main__.py, forch/utils.py
* `get_logger(name)` returns the same instance when getting the logger with the same `name`. So making a change to avoid adding new file handler to logger if it is already added, otherwise there will be many open log files.
* Using `WatchedFileHandler` instead of `FileHandler` since we are using logrotate.
* Moved global variable `LOGGER` in `__main__.py` to local variables in functions since when we import his file we should not import his global variable
=> Avoid reaptedly adding log handlers

forch/faucet_state_collector.py
Excluding the north face devices learned on the egress and trunk ports when calculating the number of access hosts.
=> Only consider access devices in hosts counting

forch/http_server.py
The `Requesthandler` handles the HTTP request in do_GET() which is called in the parent constructor (`super().__init__()`). The problem was that the logger is initialized after parent constructor is called. As a result, it will complain "handler has no _logger attribute" when handling the http request, since the logger is not initialized yet.
=> Initialize logger before calling parent constructor in RequestHandler

forch/forchestrator.py
Avoid exception in get_system_state() which is caused by copying NoneType to protobuf message.
=> Initialize faucet_config_summary with empty protobuf message

.pylintrc, forch/device_report_server.py, forch/faucet_state_collector.py, forch/forchestrator.py, forch/port_state_manager.py, testing/python_lib/test_fot.py
* Added interface `DeviceStateReporter`
* Make Forch only report applied vlan to DAQ, when device has both static and dynamic vlan assignment
=> Refactor DeviceReportServer methods with interface

forch/local_state_collector.py
There is a problem with direct assignment in local_state_collector.py at line 327. When calculating the new vrrp_state map, if the state does not change, the `change_count` and `last_change` fields will be empty. If we directly assign the new vrrp_state map to `self._vrrp_state`, the change_count and last_change information would be lost.
With `update()`, `self._vrrp_state` can preserve the entries that are not changed.
=> Update vrrp_state map in place

forch/faucetizer.py, forch/forchestrator.py, forch/port_state_manager.py, testing/python_lib/test_faucetizer.py
The main idea of this change is that if either of these two configs are invalid (specifed acl/file does not existing, file reading error, etc.), Forch will continue to run with static and dynamic auth disabled. Forch will also display the detailed error on NOAH.
=> Validate tail_acl and segments_vlans_file during Forch initialization

forch/cpn_state_collector.py, forch/faucetizer.py, forch/forchestrator.py, forch/port_state_manager.py, testing/python_lib/build_config.py, testing/python_lib/test_fot.py, topo/bond/faucet/faucet.yaml, topo/dva/forch/behaviors.yaml, topo/fot/forch/faucet.yaml, topo/fot/forch/forch.yaml, topo/scale/faucet/faucet.yaml
There was an issue where static device behavior was defined with uppercase MAC but the corresponding dynamic device placement was learned with lowercase MAC. As a result PortStatemanager treated them as different devices.
=> Always use lowercase MAC in PortStateManager

.github/workflows/main.yaml
Actions revert to faucetsdn if URL isnt specified. Can't push gmasterr tags to faucetsdn
=> Add repo URL secet to all jobs

bin/setup_remote
This is a minor change to forch to enable CI testing from DAQ to run FOT inside of the DAQ CI (will be in a separate DAQ PR).
=> Fetch target_version
